fix: tab behaviour on editor #42
kartik-madhak/noter pull request #46
Opened 2023-10-19 13:30 UTC by Tobshub

This pr fixes #42 by using codemirror's builtin `indentWithTab` command as an extension.

2023-10-19 18:54 UTC, Tobshub commented
@kartik-madhak requesting review

2023-10-20 05:24 UTC, kartik-madhak requested changes
Hey, the implementation looks good! 
But could you move this keymap to src/components/Editor/customKeymap.ts file instead? That would make it much cleaner!

2023-10-20 06:04 UTC, Tobshub commented
I've put the `indentWithTab` command in the `customKeymap.ts` file :)

2023-10-20 06:37 UTC, kartik-madhak approved these changes

2023-10-20 06:40 UTC, merged